version: '2'

services:

  eureka-server:
    image: spring-boot-starter-tomcat/eureka-server
    hostname: eureka
    ports:
      - "8761:8080"
    networks:
      - cloud

  admin-server:
    image: spring-boot-starter-tomcat/admin-server
    ports:
      - "8083:8080"
    links:
      - eureka-server:eureka
    networks:
      - cloud

  cloud-service:
    image: spring-boot-starter-tomcat/cloud-service
#    ports:
#      - "8080:8080"
    links:
      - eureka-server:eureka
    networks:
      - cloud

  cloud-client:
    image: spring-boot-starter-tomcat/cloud-client
    ports:
      - "8081:8080"
    links:
      - eureka-server:eureka
    networks:
      - cloud

  cloud-metrics:
    image: spring-boot-starter-tomcat/cloud-metrics
    ports:
      - "8082:8080"
    links:
      - eureka-server:eureka
    networks:
      - cloud


networks:
  cloud:
    driver: bridge
