#server.port=8080
server:
  port: 8080

spring:
  boot:
    admin:
      url: ${admin.server.url:http://localhorst:8083}
  application:
    name: helloService
  cloud:
    consul:
      bus:
        eventDelay: 3000