server:
  port: 8081

spring:
  boot:
    admin:
      url: ${admin.server.url}
  application:
    name: helloClient
  cloud:
    consul:
      discovery:
        register: false
      bus:
        eventDelay: 3000
